use std::{
    fs,
    io::Write,
    path::{Path, PathBuf},
};

const GENERATED_MARKER: &str = ".mocu-generated-resource-bundle";
const EXCLUDED_DIRS: &[&str] = &["node_modules", ".mocu", ".git", "__pycache__", "target", ".venv"];

fn copy_filtered(source: &Path, destination: &Path) -> std::io::Result<()> {
    if !source.exists() {
        fs::create_dir_all(destination)?;
        return Ok(());
    }
    fs::create_dir_all(destination)?;
    for entry in fs::read_dir(source)? {
        let entry = entry?;
        let name = entry.file_name();
        let name_text = name.to_string_lossy();
        if EXCLUDED_DIRS.contains(&name_text.as_ref())
            || name_text.ends_with(".egg-info")
            || name_text.starts_with("docs.db-")
            || name_text == "docs.db"
            || name_text.ends_with(".pyc")
        {
            continue;
        }
        let file_type = entry.file_type()?;
        if file_type.is_symlink() {
            continue;
        }
        let target = destination.join(&name);
        if file_type.is_dir() {
            copy_filtered(&entry.path(), &target)?;
        } else if file_type.is_file() {
            fs::copy(entry.path(), target)?;
        }
    }
    Ok(())
}

fn prepare_install_resources() -> Result<(), Box<dyn std::error::Error>> {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR")?);
    let project_root = manifest.parent().expect("src-tauri must be inside project root");
    let source = project_root.join("install-resources");
    let staged = manifest.join("target").join("install-resources-bundle");
    let marker = staged.join(GENERATED_MARKER);

    println!("cargo:rerun-if-changed={}", source.display());
    println!("cargo:rerun-if-changed=build.rs");

    if staged.exists() {
        if !marker.is_file() {
            return Err(format!("Refusing to replace {} because it is not marked as generated by Mocu's build script", staged.display()).into());
        }
        fs::remove_dir_all(&staged)?;
    }
    fs::create_dir_all(&staged)?;
    fs::File::create(staged.join(GENERATED_MARKER))?.write_all(b"generated by src-tauri/build.rs\n")?;

    for folder in ["agents", "docs", "skills", "extensions-default", "extension-system"] {
        copy_filtered(&source.join(folder), &staged.join(folder))?;
    }
    Ok(())
}

fn main() {
    if let Err(error) = prepare_install_resources() {
        panic!("failed to prepare bundled install resources: {error}");
    }
    tauri_build::build()
}
