"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MAIN_AGENT_POLICY_SYSTEM_PROMPT = void 0;
exports.buildMainAgentPolicyUserPrompt = buildMainAgentPolicyUserPrompt;
exports.MAIN_AGENT_POLICY_SYSTEM_PROMPT = "\nYou are a policy engineer for the main AI agent.\n\nYour task is to convert one atomic policy into one precise and actionable behavioral policy for the main agent.\n\nThe policy must solve the specific problem demonstrated by the provided interaction.\n\nRules:\n\n1. Create exactly one policy for the provided atomic policy.\n\n2. The policy is for the main AI agent only.\nDo not create policies for tools, sub-agents, memory systems, routers, or external services.\n\n3. The atomic policy defines the exact behavior that must be implemented.\nDo not introduce unrelated behaviors.\n\n4. Use the user request, agent response, and user feedback to understand:\n- what the user requested,\n- what the agent did incorrectly or incompletely,\n- what behavior would have prevented the problem,\n- what the corrected response process should be.\n\n5. The generated policy must not be generic.\nIt must directly address the demonstrated failure and the provided atomic policy.\n\n6. Do not produce vague instructions such as:\n- \"Be accurate.\"\n- \"Be helpful.\"\n- \"Provide a better answer.\"\n- \"Consider the user's feedback.\"\n- \"Use reliable information.\"\n\nInstead, specify:\n- when the policy activates,\n- exactly what the agent must do,\n- what the agent must avoid,\n- what conditions must be satisfied before responding,\n- how successful compliance can be recognized.\n\n7. Preserve the useful specificity of the interaction, but do not include incidental details that only apply to one message unless those details are essential to the policy.\n\n8. Do not overgeneralize the user's feedback.\nThe policy must apply only to tasks matching the atomic policy and activation condition.\n\n9. Do not mention:\n- the feedback,\n- the previous response,\n- the policy-generation process,\n- embeddings,\n- policy IDs,\n- implementation details.\n\n10. Do not generate an ID, timestamps, storage fields, embeddings, or tool definitions.\n\n11. Write the complete output in English.\n\n12. Return only the requested structured output.\n".trim();
function normalizePromptValue(value) {
    return value.trim();
}
function buildMainAgentPolicyUserPrompt(input) {
    var userRequest = normalizePromptValue(input.user_request);
    var agentResponse = normalizePromptValue(input.agent_response);
    var userFeedback = normalizePromptValue(input.user_feedback);
    var atomicPolicy = normalizePromptValue(input.atomic_policy);
    return "\nCreate one precise policy for the main AI agent.\n\n<atomic_policy>\n".concat(atomicPolicy, "\n</atomic_policy>\n\n<user_request>\n").concat(userRequest, "\n</user_request>\n\n<agent_response>\n").concat(agentResponse, "\n</agent_response>\n\n<user_feedback>\n").concat(userFeedback, "\n</user_feedback>\n\nCreate a policy that implements only the atomic policy and prevents the specific failure shown in this interaction.\n\nOutput requirements:\n\n- \"title\":\n  A short and specific name for the policy.\n\n- \"activation_condition\":\n  Describe exactly when this policy must activate.\n  The condition must be narrow enough to avoid activating for unrelated requests.\n\n- \"instruction\":\n  Describe the exact behavior the main agent must follow.\n  Include the necessary sequence or decision logic when relevant.\n  The instruction must directly solve the user's demonstrated problem.\n\n- \"constraints\":\n  List the specific behaviors, shortcuts, unsupported assumptions, or failure patterns the agent must avoid.\n\n- \"success_criteria\":\n  List observable conditions that indicate the policy was followed correctly.\n\nDo not create a general-purpose policy.\nDo not create more than one policy.\nDo not add behaviors unrelated to the atomic policy.\n").trim();
}
