// window/windowIndexes.ts

import { textSimilarity } from "../../../../services/ai/tools/textSimilarity";
import type {
  MemoryWindow,
  Turn,
  WindowIndexes,
} from "./types";
import {
  getErrorMessage,
  uniqueStrings,
} from "./helpers";
import { createWindowMainSubject } from "./windowSubject";

/* -------------------------------------------------------------------------- */
/* Embedding Text                                                             */
/* -------------------------------------------------------------------------- */

/**
 * Builds the text that is sent to the embedding model.
 *
 * The text is a combination of all Window subjects and keywords.
 */
export function createWindowEmbeddingText(
  subjects: string[],
  keywords: string[],
): string {
  return [
    `Subject: ${subjects.join("; ")}`,
    `Keywords: ${keywords.join(", ")}`,
  ].join("\n");
}

async function buildWindowEmbedding(
  subjects: string[],
  keywords: string[],
): Promise<number[]> {
  const embeddingText =
    createWindowEmbeddingText(
      subjects,
      keywords,
    );

  try {
    return await textSimilarity.embedText(
      embeddingText,
    );
  } catch (error) {
    throw new Error(
      `Could not create the Window embedding: ${getErrorMessage(error)}`,
    );
  }
}

/* -------------------------------------------------------------------------- */
/* Index Management                                                           */
/* -------------------------------------------------------------------------- */

/**
 * Creates the indexes of a new Window from its first Turn.
 *
 * With a single Turn, the Turn subject is the main subject and no LLM
 * call is needed.
 */
export async function createWindowIndexes(
  turn: Turn,
): Promise<WindowIndexes> {
  const subjects = uniqueStrings([
    turn.indexes.subject,
  ]);

  const keywords = uniqueStrings(
    turn.indexes.keywords,
  );

  return {
    subjects,
    keywords,
    types: uniqueStrings([
      turn.indexes.type,
    ]),
    embedding: await buildWindowEmbedding(
      subjects,
      keywords,
    ),
  };
}

/**
 * Updates the indexes of a Window after a new Turn is appended.
 *
 * - The single main subject is regenerated by the LLM from the
 *   subjects of ALL Turns in the Window (including the new Turn), so
 *   it always reflects the combined meaning of every Turn.
 * - Keywords, types, and entities are unique unions of all Turns.
 * - The embedding is created from the main subject and keywords using
 *   the embedding model.
 */
export async function updateWindowIndexes(
  window: MemoryWindow,
  turn: Turn,
): Promise<WindowIndexes> {
  const allTurnSubjects = [
    ...window.turns.map(
      (existingTurn) =>
        existingTurn.indexes.subject,
    ),
    turn.indexes.subject,
  ];

  const mainSubject =
    await createWindowMainSubject(
      allTurnSubjects,
    );

  const subjects = uniqueStrings([
    mainSubject,
  ]);

  const keywords = uniqueStrings([
    ...window.indexes.keywords,
    ...turn.indexes.keywords,
  ]);

  return {
    subjects,
    keywords,
    types: uniqueStrings([
      ...window.indexes.types,
      turn.indexes.type,
    ]),
    embedding: await buildWindowEmbedding(
      subjects,
      keywords,
    ),
  };
}
