import {
  BaseDirectory,
  exists,
  mkdir,
  writeTextFile,
} from "@tauri-apps/plugin-fs";

import {
  analyzeMemoryRelationships,
  type MemoryRelationshipAnalysis,
} from "./analyzeMemoryRelationships";

import {
  enrichAtomicMemory,
  type MemoryNode,
} from "./enrichMemory";

import { findSimilarMemories } from "./findSimilarMemories";

import {
  evolveNeighborContext,
  type MemoryLink,
  type MemoryNodeWithLinks,
  type MemoryRelationship,
} from "./evolveNeighborContext";

const MEMORY_DIRECTORY = "memory";

const MINIMUM_RELATIONSHIP_CONFIDENCE = 0.5;

const MEMORY_RELATIONSHIPS = [
  "COMPLEMENTS",
  "CONTRADICTS",
  "RELATED",
  "DUPLICATE",
] as const satisfies readonly MemoryRelationship[];

const NON_LINK_RELATIONSHIP = "UNRELATED";

export type CreateMemoryAction =
  | "CREATED_NEW"
  | "REUSED_EXISTING";

export type CreatedMemoryResult = {
  /**
   * The newly created memory or the existing canonical memory
   * that was reused when a duplicate was detected.
   */
  memory: MemoryNodeWithLinks;

  /**
   * Indicates whether a new memory file was created.
   */
  wasNewMemorySaved: boolean;

  /**
   * Describes the final action performed by the pipeline.
   */
  action: CreateMemoryAction;

  /**
   * Number of memories returned by the similarity search.
   */
  similarMemoriesCount: number;

  /**
   * Relationship analyses generated for the prepared memory.
   *
   * This can include UNRELATED analyses even though they are not
   * converted into stored memory links.
   */
  relationshipAnalyses: MemoryRelationshipAnalysis[];

  /**
   * Relative path of the newly created file or the reused existing file.
   */
  filePath: string;

  /**
   * ID of the newly created memory or the reused canonical memory.
   */
  finalMemoryId: string;

  /**
   * ID originally generated by enrichAtomicMemory.
   *
   * This can differ from finalMemoryId when an existing duplicate
   * memory is reused.
   */
  preparedMemoryId: string;

  /**
   * Information about the reused memory when a duplicate is detected.
   */
  duplicate:
    | {
        memoryId: string;
        fileName: string;
      }
    | null;
};

function createAbortError(): DOMException {
  return new DOMException(
    "The operation was cancelled.",
    "AbortError",
  );
}

function throwIfAborted(
  signal?: AbortSignal,
): void {
  if (signal?.aborted) {
    throw createAbortError();
  }
}

/**
 * Creates a memory from an atomic memory statement.
 *
 * Pipeline:
 * 1. Enrich the atomic memory.
 * 2. Find similar stored memories.
 * 3. Analyze relationships.
 * 4. Exclude UNRELATED analyses from graph links.
 * 5. Create valid memory links.
 * 6. Check whether an existing duplicate should be reused.
 * 7. Save the new memory only when no readable duplicate was reused.
 *
 * Duplicate behavior:
 * - The existing memory remains the canonical memory.
 * - The existing memory is updated by evolveNeighborContext.
 * - The prepared new memory is not saved.
 * - No duplicate file is deleted.
 * - No references are redirected.
 *
 * UNRELATED behavior:
 * - UNRELATED remains available in relationshipAnalyses for diagnostics.
 * - It is not treated as an unsupported relationship.
 * - It is not converted into a MemoryLink.
 * - It is never stored inside the links array.
 *
 * Cancellation is cooperative. A Tauri file operation that has already
 * started cannot necessarily be interrupted or rolled back.
 */
export async function createMemory(
  atomicMemory: string,
  signal?: AbortSignal,
): Promise<CreatedMemoryResult> {
  throwIfAborted(signal);

  const content = atomicMemory?.trim();

  if (!content) {
    throw new Error(
      "Atomic memory content cannot be empty.",
    );
  }

  const enrichedMemory =
    await enrichAtomicMemory(
      content,
      signal,
    );

  throwIfAborted(signal);

  validatePreparedMemory(
    enrichedMemory,
  );

  const preparedMemoryId =
    enrichedMemory.id.trim();

  const similarMemories =
    await findSimilarMemories(
      enrichedMemory,
      signal,
    );

  throwIfAborted(signal);

  const relationshipAnalyses =
    await analyzeMemoryRelationships(
      enrichedMemory,
      similarMemories,
      signal,
    );

  throwIfAborted(signal);

  const initialLinks =
    createMemoryLinks(
      relationshipAnalyses,
    );

  const preparedMemory: MemoryNodeWithLinks = {
    ...enrichedMemory,
    id: preparedMemoryId,
    links: initialLinks,
  };

  throwIfAborted(signal);

  /*
   * evolveNeighborContext can either:
   * - Request that the prepared memory be saved.
   * - Reuse and update an existing duplicate memory.
   */
  const evolutionResult =
    await evolveNeighborContext(
      preparedMemory,
      signal,
    );

  throwIfAborted(signal);

  if (
    evolutionResult.shouldSaveNewMemory
  ) {
    const memoryToSave =
      normalizeMemoryForSaving(
        evolutionResult.memory,
      );

    const filePath =
      await saveMemoryFile(
        memoryToSave,
        signal,
      );

    throwIfAborted(signal);

    console.log(
      "[Memory creation] New memory saved.",
      {
        memoryId:
          memoryToSave.id,
        filePath,
        similarMemoriesCount:
          similarMemories.length,
        relationshipCount:
          relationshipAnalyses.length,
        unrelatedRelationshipCount:
          countUnrelatedRelationships(
            relationshipAnalyses,
          ),
        storedLinkCount:
          memoryToSave.links.length,
      },
    );

    return {
      memory: memoryToSave,
      wasNewMemorySaved: true,
      action: "CREATED_NEW",
      similarMemoriesCount:
        similarMemories.length,
      relationshipAnalyses,
      filePath,
      finalMemoryId:
        memoryToSave.id,
      preparedMemoryId,
      duplicate: null,
    };
  }

  const duplicateFileName =
    validateMemoryFileName(
      evolutionResult.duplicateFileName,
    );

  const existingFilePath =
    createMemoryFilePath(
      duplicateFileName,
    );

  console.log(
    "[Memory creation] Existing duplicate memory reused. The prepared new memory was not saved.",
    {
      preparedMemoryId,
      existingMemoryId:
        evolutionResult.duplicateMemoryId,
      existingFileName:
        duplicateFileName,
      existingFilePath,
      similarMemoriesCount:
        similarMemories.length,
      relationshipCount:
        relationshipAnalyses.length,
      unrelatedRelationshipCount:
        countUnrelatedRelationships(
          relationshipAnalyses,
        ),
    },
  );

  return {
    memory: evolutionResult.memory,
    wasNewMemorySaved: false,
    action: "REUSED_EXISTING",
    similarMemoriesCount:
      similarMemories.length,
    relationshipAnalyses,
    filePath: existingFilePath,
    finalMemoryId:
      evolutionResult.duplicateMemoryId,
    preparedMemoryId,
    duplicate: {
      memoryId:
        evolutionResult.duplicateMemoryId,
      fileName:
        duplicateFileName,
    },
  };
}

/**
 * Converts valid relationship analyses into memory links.
 *
 * A relationship is excluded when:
 * - It is UNRELATED.
 * - Its relationship type is unsupported.
 * - Its target ID is invalid.
 * - Its target file name is invalid.
 * - Its confidence is not finite.
 * - Its confidence is below the configured threshold.
 *
 * UNRELATED is a valid analysis result, but it does not represent
 * a graph edge and therefore must not be stored as a MemoryLink.
 *
 * Duplicate links are retained at this stage because
 * evolveNeighborContext needs them to detect existing memories.
 */
function createMemoryLinks(
  relationshipAnalyses: MemoryRelationshipAnalysis[],
): MemoryLink[] {
  const createdAt =
    new Date().toISOString();

  const links: MemoryLink[] = [];

  for (
    const relationshipAnalysis of
    relationshipAnalyses
  ) {
    const {
      targetFileName,
      targetMemoryId,
      similarity,
      analysis,
    } = relationshipAnalysis;

    const relationship =
      analysis.relationship;

    /*
     * UNRELATED is a valid classification result, not an error.
     *
     * It is intentionally ignored without producing a warning because
     * unrelated memories must not create graph links.
     */
    if (
      isUnrelatedRelationship(
        relationship,
      )
    ) {
      continue;
    }

    if (
      !isMemoryRelationship(
        relationship,
      )
    ) {
      console.warn(
        "[Memory creation] A relationship analysis was ignored because its relationship type is unsupported.",
        {
          relationship,
          targetMemoryId,
          targetFileName,
        },
      );

      continue;
    }

    const confidence =
      Number(analysis.confidence);

    if (
      !Number.isFinite(confidence) ||
      confidence <
        MINIMUM_RELATIONSHIP_CONFIDENCE
    ) {
      continue;
    }

    const normalizedTargetId =
      normalizeMemoryId(
        targetMemoryId,
      );

    const normalizedTargetFileName =
      getSafeMemoryFileName(
        targetFileName,
      );

    if (
      !normalizedTargetId ||
      !normalizedTargetFileName
    ) {
      console.warn(
        "[Memory creation] A relationship analysis was ignored because its target is invalid.",
        {
          targetMemoryId,
          targetFileName,
        },
      );

      continue;
    }

    const reason =
      typeof analysis.reason ===
        "string"
        ? analysis.reason.trim()
        : "";

    links.push({
      targetId:
        normalizedTargetId,
      targetFileName:
        normalizedTargetFileName,
      relationship,
      similarity:
        normalizeScore(similarity),
      confidence:
        normalizeScore(confidence),
      reason,
      createdAt,
    });
  }

  return mergeCreatedLinks(
    links,
  );
}

/**
 * Checks whether an analysis result means that no graph link should
 * be created.
 *
 * The comparison is case-insensitive and ignores surrounding whitespace
 * so values such as " unrelated " are also handled safely.
 */
function isUnrelatedRelationship(
  relationship: unknown,
): boolean {
  return (
    typeof relationship ===
      "string" &&
    relationship
      .trim()
      .toUpperCase() ===
      NON_LINK_RELATIONSHIP
  );
}

/**
 * Counts UNRELATED analyses for diagnostic logging.
 *
 * These analyses remain in relationshipAnalyses but never enter
 * the stored links array.
 */
function countUnrelatedRelationships(
  relationshipAnalyses: MemoryRelationshipAnalysis[],
): number {
  let count = 0;

  for (
    const relationshipAnalysis of
    relationshipAnalyses
  ) {
    if (
      isUnrelatedRelationship(
        relationshipAnalysis
          .analysis
          .relationship,
      )
    ) {
      count += 1;
    }
  }

  return count;
}

/**
 * Removes duplicate relationship links that point to the same target.
 *
 * The strongest link is selected by:
 * 1. Relationship priority.
 * 2. Similarity.
 * 3. Confidence.
 */
function mergeCreatedLinks(
  links: MemoryLink[],
): MemoryLink[] {
  const linksByTarget =
    new Map<string, MemoryLink>();

  for (const link of links) {
    const targetKey =
      `${link.targetId}::${link.targetFileName}`;

    const existingLink =
      linksByTarget.get(
        targetKey,
      );

    if (
      !existingLink ||
      shouldReplaceLink(
        link,
        existingLink,
      )
    ) {
      linksByTarget.set(
        targetKey,
        link,
      );
    }
  }

  return [
    ...linksByTarget.values(),
  ].sort(compareMemoryLinks);
}

function shouldReplaceLink(
  candidate: MemoryLink,
  existing: MemoryLink,
): boolean {
  const candidatePriority =
    getRelationshipPriority(
      candidate.relationship,
    );

  const existingPriority =
    getRelationshipPriority(
      existing.relationship,
    );

  if (
    candidatePriority !==
    existingPriority
  ) {
    return (
      candidatePriority >
      existingPriority
    );
  }

  if (
    candidate.similarity !==
    existing.similarity
  ) {
    return (
      candidate.similarity >
      existing.similarity
    );
  }

  return (
    candidate.confidence >
    existing.confidence
  );
}

function getRelationshipPriority(
  relationship: MemoryRelationship,
): number {
  switch (relationship) {
    case "DUPLICATE":
      return 4;

    case "CONTRADICTS":
      return 3;

    case "COMPLEMENTS":
      return 2;

    case "RELATED":
      return 1;

    default:
      return 0;
  }
}

function compareMemoryLinks(
  first: MemoryLink,
  second: MemoryLink,
): number {
  const relationshipPriorityDifference =
    getRelationshipPriority(
      second.relationship,
    ) -
    getRelationshipPriority(
      first.relationship,
    );

  if (
    relationshipPriorityDifference !== 0
  ) {
    return relationshipPriorityDifference;
  }

  const similarityDifference =
    second.similarity -
    first.similarity;

  if (
    similarityDifference !== 0
  ) {
    return similarityDifference;
  }

  const confidenceDifference =
    second.confidence -
    first.confidence;

  if (
    confidenceDifference !== 0
  ) {
    return confidenceDifference;
  }

  return first.targetId.localeCompare(
    second.targetId,
  );
}

/**
 * Checks whether a relationship can be stored as a memory link.
 *
 * UNRELATED intentionally returns false because it is not included
 * in MEMORY_RELATIONSHIPS.
 */
function isMemoryRelationship(
  relationship: unknown,
): relationship is MemoryRelationship {
  return (
    typeof relationship ===
      "string" &&
    MEMORY_RELATIONSHIPS.includes(
      relationship as MemoryRelationship,
    )
  );
}

/**
 * Normalizes a numeric similarity or confidence score.
 *
 * Invalid values become zero. Values outside the zero-to-one range
 * are clamped to keep stored memory files consistent.
 */
function normalizeScore(
  value: unknown,
): number {
  const numericValue =
    Number(value);

  if (
    !Number.isFinite(
      numericValue,
    )
  ) {
    return 0;
  }

  return Math.min(
    1,
    Math.max(
      0,
      numericValue,
    ),
  );
}

function normalizeMemoryId(
  value: unknown,
): string | null {
  if (
    typeof value !== "string"
  ) {
    return null;
  }

  const normalizedValue =
    value.trim();

  if (!normalizedValue) {
    return null;
  }

  if (
    !isSafeMemoryId(
      normalizedValue,
    )
  ) {
    return null;
  }

  return normalizedValue;
}

/**
 * Validates the memory created by enrichAtomicMemory before any
 * graph or file operation begins.
 */
function validatePreparedMemory(
  memory: MemoryNode,
): void {
  if (
    !memory ||
    typeof memory !== "object"
  ) {
    throw new Error(
      "The enrichment stage returned an invalid memory.",
    );
  }

  if (
    typeof memory.id !== "string" ||
    !memory.id.trim()
  ) {
    throw new Error(
      "The enriched memory has no valid ID.",
    );
  }

  validateMemoryId(
    memory.id,
  );
}

/**
 * Ensures the memory has a valid ID and a valid links array before saving.
 *
 * This provides a second protection layer. Even if an invalid or
 * UNRELATED link somehow enters memory.links, it will not be saved.
 */
function normalizeMemoryForSaving(
  memory: MemoryNodeWithLinks,
): MemoryNodeWithLinks {
  if (
    !memory ||
    typeof memory !== "object"
  ) {
    throw new Error(
      "The memory cannot be saved because it is invalid.",
    );
  }

  validateMemoryId(
    memory.id,
  );

  const memoryId =
    memory.id.trim();

  const memoryFileName =
    createMemoryFileName(
      memoryId,
    );

  const links =
    Array.isArray(memory.links)
      ? mergeCreatedLinks(
          memory.links.filter(
            (link) =>
              isValidLinkForSaving(
                link,
                memoryId,
                memoryFileName,
              ),
          ),
        )
      : [];

  return {
    ...memory,
    id: memoryId,
    links,
  };
}

function isValidLinkForSaving(
  link: MemoryLink,
  memoryId: string,
  memoryFileName: string,
): boolean {
  if (
    !link ||
    typeof link !== "object"
  ) {
    return false;
  }

  /*
   * This explicitly blocks UNRELATED if malformed external data
   * somehow reaches the final saving stage.
   */
  if (
    isUnrelatedRelationship(
      link.relationship,
    )
  ) {
    return false;
  }

  if (
    !isMemoryRelationship(
      link.relationship,
    )
  ) {
    return false;
  }

  const targetId =
    normalizeMemoryId(
      link.targetId,
    );

  const targetFileName =
    getSafeMemoryFileName(
      link.targetFileName,
    );

  if (
    !targetId ||
    !targetFileName
  ) {
    return false;
  }

  const confidence =
    Number(link.confidence);

  if (
    !Number.isFinite(confidence) ||
    confidence <
      MINIMUM_RELATIONSHIP_CONFIDENCE
  ) {
    return false;
  }

  const pointsToItself =
    targetId === memoryId ||
    targetFileName ===
      memoryFileName;

  return !pointsToItself;
}

/**
 * Saves a new memory as memory/{memory.id}.json inside AppData.
 *
 * This function must only be called when evolveNeighborContext returns
 * shouldSaveNewMemory as true.
 */
async function saveMemoryFile(
  memory: MemoryNodeWithLinks,
  signal?: AbortSignal,
): Promise<string> {
  throwIfAborted(signal);

  validateMemoryId(
    memory.id,
  );

  await ensureMemoryDirectoryExists(
    signal,
  );

  throwIfAborted(signal);

  const fileName =
    createMemoryFileName(
      memory.id,
    );

  const filePath =
    createMemoryFilePath(
      fileName,
    );

  const serializedMemory =
    JSON.stringify(
      memory,
      null,
      2,
    );

  try {
    await writeTextFile(
      filePath,
      serializedMemory,
      {
        baseDir:
          BaseDirectory.AppData,
      },
    );
  } catch (error) {
    console.error(
      "[Memory creation] Failed to save the new memory file.",
      {
        memoryId:
          memory.id,
        filePath,
        error,
      },
    );

    throw new Error(
      `Failed to save memory "${memory.id}": ${getErrorMessage(error)}`,
    );
  }

  throwIfAborted(signal);

  return filePath;
}

/**
 * Creates the memory directory when it does not already exist.
 */
async function ensureMemoryDirectoryExists(
  signal?: AbortSignal,
): Promise<void> {
  throwIfAborted(signal);

  let memoryDirectoryExists: boolean;

  try {
    memoryDirectoryExists =
      await exists(
        MEMORY_DIRECTORY,
        {
          baseDir:
            BaseDirectory.AppData,
        },
      );
  } catch (error) {
    throw new Error(
      `Failed to check the memory directory: ${getErrorMessage(error)}`,
    );
  }

  throwIfAborted(signal);

  if (memoryDirectoryExists) {
    return;
  }

  try {
    await mkdir(
      MEMORY_DIRECTORY,
      {
        baseDir:
          BaseDirectory.AppData,
        recursive: true,
      },
    );
  } catch (error) {
    /*
     * Another concurrent operation may have created the directory after
     * the exists check. Check it once more before treating mkdir as failed.
     */
    throwIfAborted(signal);

    let directoryNowExists: boolean;

    try {
      directoryNowExists =
        await exists(
          MEMORY_DIRECTORY,
          {
            baseDir:
              BaseDirectory.AppData,
          },
        );
    } catch (existsError) {
      throw new Error(
        `Failed to create or recheck the memory directory: ${getErrorMessage(
          existsError,
        )}`,
      );
    }

    throwIfAborted(signal);

    if (!directoryNowExists) {
      throw new Error(
        `Failed to create the memory directory: ${getErrorMessage(error)}`,
      );
    }
  }

  throwIfAborted(signal);
}

/**
 * Validates an internally generated memory ID.
 *
 * IDs are not silently modified because changing an ID here would make
 * memory IDs and link target file names inconsistent.
 */
function validateMemoryId(
  memoryId: string,
): void {
  if (
    typeof memoryId !== "string" ||
    !memoryId.trim()
  ) {
    throw new Error(
      "Memory ID is invalid.",
    );
  }

  const normalizedMemoryId =
    memoryId.trim();

  if (
    !isSafeMemoryId(
      normalizedMemoryId,
    )
  ) {
    throw new Error(
      `Memory ID contains unsupported characters: "${normalizedMemoryId}".`,
    );
  }
}

function isSafeMemoryId(
  memoryId: string,
): boolean {
  return /^[a-zA-Z0-9_-]+$/.test(
    memoryId,
  );
}

function createMemoryFileName(
  memoryId: string,
): string {
  validateMemoryId(
    memoryId,
  );

  return `${memoryId.trim()}.json`;
}

function validateMemoryFileName(
  fileName: string,
): string {
  const safeFileName =
    getSafeMemoryFileName(
      fileName,
    );

  if (!safeFileName) {
    throw new Error(
      `Memory file name is invalid: "${fileName}".`,
    );
  }

  return safeFileName;
}

function getSafeMemoryFileName(
  fileName: unknown,
): string | null {
  if (
    typeof fileName !== "string" ||
    !fileName.trim()
  ) {
    return null;
  }

  const normalizedFileName =
    fileName.trim();

  if (
    normalizedFileName.includes(
      "/",
    ) ||
    normalizedFileName.includes(
      "\\",
    )
  ) {
    return null;
  }

  if (
    !/^[a-zA-Z0-9_-]+\.json$/.test(
      normalizedFileName,
    )
  ) {
    return null;
  }

  return normalizedFileName;
}

function createMemoryFilePath(
  fileName: string,
): string {
  const safeFileName =
    validateMemoryFileName(
      fileName,
    );

  return `${MEMORY_DIRECTORY}/${safeFileName}`;
}

function getErrorMessage(
  error: unknown,
): string {
  if (
    error instanceof Error
  ) {
    return error.message;
  }

  if (
    typeof error === "string"
  ) {
    return error;
  }

  try {
    return JSON.stringify(
      error,
    );
  } catch {
    return String(error);
  }
}